version: '3'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - C:\Users\SSAFY\Desktop\pjt\docker_mysql:/var/lib/mysql
      #- C:\Users\rmstn\Desktop\pjt\docker_mysql:/var/lib/mysql
      # - /Users/debeujun/Desktop/pjt\docker_mysql:/var/lib/mysql
      # - ${MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d
      # - ${MYSQL_DEFAULT_CONFIG_FILE}:/etc/my.cnf

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  kurento:
    image: kurento/kurento-media-server:7.0.0
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
      - GST_DEBUG="${GST_DEBUG:-2},webrtcendpoint:5,kmswebrtcsession:5,kmsiceniceagent:5"
      - G_MESSAGES_DEBUG="libnice,libnice-stun"
    ports:
      - "8888:8888"
      - "5000-5050:5000-5050/udp"
    restart: unless-stopped
#    volumes:
#      - C:\kurentolocal:/etc/kurento/modules/
